services:
  # Backend API service
  - type: web
    name: greenlight-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CRYPTO_PAY_API_TOKEN
        sync: false

  # Telegram Bot service
  - type: web
    name: greenlight-bot
    env: node
    plan: starter
    buildCommand: cd bot && npm install
    startCommand: cd bot && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: API_URL
        sync: false
      - key: CRYPTO_PAY_API_TOKEN
        sync: false

  # Frontend static site (исправлено)
  - type: web
    name: greenlight-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_WS_URL
        sync: false
